### ISSUE TITLE
如何跳过空格

### ISSUE THREAD

**Issue by SongshGeo** [SharzyL/cjk-word-handler#2]
感谢大佬贡献！这个插件对 VSCode 写 LaTeX 的我帮助很大。
有个问题是安装插件后，原本的英文分词 ctrl+left/right 可以跳过单词之间的空格，现在不可以了，需要按两次才能跳过一个英文单词，略降低效率，这个有没有办法解决一下？

**Comment by SharzyL** [comment]
能否提供一下具体复现的方式以及期望的行为？

**Comment by SongshGeo** [comment]
你好，感谢您对该拓展的维护以及最近的更新。

复现方式，对于一句英文：
*I*`word1` `word2` `word3` `word4`
如果我禁用该插件，对于英文单词构成的句子，使用快捷键（mac系统）option+right四次就可以到达最右端：

`word1`*I* `word2` `word3` `word4`
`word1` `word2`*I* `word3` `word4`
`word1` `word2` `word3`*I* `word4`
`word1` `word2` `word3` `word4`*I*

这和绝大多数的英语分词行为（比如GitHub）是完全一致的。

如果启用该插件，则需要7次才能到达这个英文句子的右侧

`word1`*I* `word2` `word3` `word4`
`word1` *I*`word2` `word3` `word4`
`word1` `word2`*I* `word3` `word4`
`word1` `word2` *I*`word3` `word4`
`word1` `word2` `word3`*I* `word4`
`word1` `word2` `word3` *I*`word4`
`word1` `word2` `word3` `word4`*I*

看起来是把英文单词之间的空字符处理成了一次跳跃。

预期行为：仅改变中文句子的分词跳跃方式，不改变英文句子的。

**Comment by SharzyL** [comment]
我在 Linux 和 macOS 上均未能复现这个问题，跳转方式是符合期望的。我使用的是 VSCode 1.81.1 和 CJK workd handler 0.2.0，没有启用其它插件。

参照对应的源码，在处理向后跳转时会先跳过空格，然后向右搜索直至字符类别发生改变。

https://github.com/SharzyL/cjk-word-handler/blob/eb5db3f5baee7a2f56fe6eb02a8ce2850f98eeca/src/extension.ts#L93-L103

能否提供更详细的复现方式？

**Comment by SongshGeo** [comment]
禁用所有工作区插件后，又做了一次测试：

VSCode版本v1.85.1，插件版本0.2.0, `.tex` 和 `.md`文件中都存在该问题。请见动图：

**启用插件的时候**
![CleanShot2024-01-14at08.29.02](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202024-01-14%20at%2008.29.02.gif)

**关闭插件的时候**
![CleanShot2024-01-14at08.29.34](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202024-01-14%20at%2008.29.34.gif)

**Comment by SharzyL** [comment]
我猜这个问题可能和 wordSeparators 选项有关，能看一下你的设置里面是否修改了 `editor.wordSeparators` ，以及检查一下是否有其它可能相关的设置被修改了吗？

**Comment by SongshGeo** [comment]
非常感谢指路！确实在注释掉`editor.wordSeparators`设置后恢复了正常。之前没发现这款插件前一直通过这个设置来修改分词行为的。
